eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: 127.0.0.1

server:
  port: 8084

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  application:
    name: product-eureka-client

logging:
  level:
    root: debug